Feat: Add example test failure and actionlint exclusion
Also, update examples to the appropriate (lower) case.
Minor formatting updates to example README.md file.

Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -36,10 +36,29 @@ jobs:
 
       - name: "Running local action: ${{ github.repository }}"
         uses: ./
+        with:
+          input: "test input 💬"
 
-      - name: "Validating local action: ${{ github.repository }}"
+      - name: "Validated local action: ${{ github.repository }}"
         shell: bash
         run: |
           # Local action validation
-          echo "Validating local action: ${{ github.repository }}"
+          echo "Validated local action: ${{ github.repository }}"
           echo "Validation step summary output" >> "$GITHUB_STEP_SUMMARY"
+
+      # yamllint disable-line rule:line-length
+      - name: "Running local action: ${{ github.repository }} [Override Failure]"
+        uses: ./
+        id: failure
+        continue-on-error: true
+        with:
+          invalid_input: "Some garbage"
+
+      # Failure testing is also important
+      - name: "Error if step above did NOT fail"
+        if: steps.failure.outcome == 'success'
+        shell: bash
+        run: |
+          # Error if step above did NOT fail
+          echo "Error: previous test step did NOT fail ❌"
+          exit 1
